### PR TITLE
Improves performance and memory footprint of vmq_reg_trie

### PR DESCRIPTION
**Pull request by mths1**
## Proposed Changes

Please describe the big picture of your changes here to communicate to the
VerneMQ team why we should accept this pull request. If it fixes a bug or
resolves a feature request, be sure to link to that issue.

## Types of Changes

What types of changes does your code introduce to this project?
_Put an `x` in the boxes that apply_

- [X] Bugfix (non-breaking change which fixes issue #1694, maybe #1944 )
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation (correction or otherwise)
- [ ] Cosmetics (whitespace, styles...)
- [ ] DevOps (Build scripts, pipelines...)

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating
the PR. If you're unsure about any of them, don't hesitate to ask on the
mailing list. We're here to help! This is simply a reminder of what we are
going to look for before merging your code._

- [ ] I have read the [CODE_OF_CONDUCT.md](https://github.com/vernemq/vernemq/blob/main/CODE_OF_CONDUCT.md) document
- [ ] All tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if needed)
- [ ] Any dependent changes have been merged and published in related repositories
- [ ] I have updated changelog (At the bottom of the release version)
- [ ] I have squashed all my commits into one before merging

## Further Comments

If this is a relatively large or complex change, kick off the discussion by
explaining why you chose the solution you did and what alternatives you
considered, etc.

### CODE REVIEW

**Comment by mths1** [comment]
Let me know what you think about how to proceed here? I could make a new view out of it, or just modify the existing code around vmq_reg_trie?

**Comment by codeadict** [comment]
@mths1 - I like to see a more detailed description of what the PR does. How `vmq_reg_trie` currently behaves in terms of memory and performance and how this PR improves it, ideally with some benchmarks/numbers around that.

**Comment by ioolkos** [comment]
@mths1 I'd add it as a new view but set it as a the default. This gives the user the ability to fall back, in case of unexpected differences.

**Comment by mths1** [comment]
Some graphs, for 100 clients subscribing to 500 topics each.

image

**Comment by mths1** [comment]
I added it as a new reg_view. I have been always bad at naming stuff, so it is now called vmq_reg_ordered_trie. Better names are welcome. I do not load it by default, as the original version still has negative impact on performance and memory footprint even when it is not the default. I will see if I can make some memory and performance plots today or tomorrow. Naming suggestions and suggestions for code improvement are always welcome :-)

**Comment by ioolkos** [comment]
Naming stuff and cache invalidation are the only hard problems, right? :)

> I do not load it by default, as the original version still has negative impact on performance and memory footprint even when it is not the default.

Hold on... the original version has negative impact on the new reg_view just because the former is loaded too?

**Comment by mths1** [comment]
Scenario:
100 clients
500 topics each
No publish

image

**Comment by mths1** [comment]
> Naming stuff and cache invalidation are the only hard problems, right? :)
> 
> > I do not load it by default, as the original version still has negative impact on performance and memory footprint even when it is not the default.
> 
> Hold on... the original version has negative impact on the new reg_view just because the former is loaded too?

Yep, because the vmq_reg_trie:init() runs which subscribes to the subscriber events as well.

**Comment by ioolkos** [comment]
Nice!
Ok, got you on the loading of multiple reg_views. We don't preload the old one then.
A user still can fallback to it with:
```
default_reg_view = vmq_reg_view
reg_views = [vmq_reg_view]
```

**Comment by ioolkos** [comment]
@mths1 I think this can move forward from draft. We can maybe rethink the parallel loading and operation of reg_views later.
I want to cut a RC for a release shortly, ideally we can have this RP merged.

**Comment by mths1** [comment]
Moved from draft to ready for review, and removed the debug code.
PS: Would be great if the REST interface would make it into the RC as well ;-)

**Review by ioolkos — APPROVED** [review]

**Pull request merged**
