### PR TITLE
Compile fixes for raspbian on Raspberry PI 32bit

### PR DESCRIPTION
**Pull request by larroy**
## Proposed Changes

Erlang version on the pi is 21.2 so bcrypt needs to be downgraded.

eleveldb fails to build. This PR: https://github.com/vernemq/eleveldb/pull/8 fixes it.  But the change is not included in rebar.

Please describe the big picture of your changes here to communicate to the
VerneMQ team why we should accept this pull request. If it fixes a bug or
resolves a feature request, be sure to link to that issue.

## Types of Changes

What types of changes does your code introduce to this project?
_Put an `x` in the boxes that apply_

- [x] Bugfix (non-breaking change which fixes issue #XXXX)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation (correction or otherwise)
- [ ] Cosmetics (whitespace, styles...)
- [ ] DevOps (Build scripts, pipelines...)

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating
the PR. If you're unsure about any of them, don't hesitate to ask on the
mailing list. We're here to help! This is simply a reminder of what we are
going to look for before merging your code._

- [ ] I have read the `CODE_OF_CONDUCT.md` document
- [ ] All tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if needed)
- [ ] Any dependent changes have been merged and published in related repositories
- [ ] I have updated changelog (At the bottom of the release version)
- [ ] I have squashed all my commits into one before merging

## Further Comments

If this is a relatively large or complex change, kick off the discussion by
explaining why you chose the solution you did and what alternatives you
considered, etc.

### CODE REVIEW

**Comment by ioolkos** [comment]
@larroy thanks :) 
 allow some time for review. (especially as it does seem to change a couple of dependencies)

**Comment by ioolkos** [comment]
@larroy the rebar.lock file locks dependencies at commit/package hash level. I haven't checked on those in detail so far, but the general point is that we probably have to do this in its own (RPi/Raspian) branch to ensure separation. 

Tests can't fetch `/vintenove/bson-erlang`, for some reason.

**Comment by codeadict** [comment]
Downgrading bcrypt will break compilation on OTP 23+

**Comment by ioolkos** [comment]
@codeadict thanks, good point.

**Comment by larroy** [comment]
I managed to compile everything in the end but got stuck trying to run the vernemq daemon and run out of time. I asked for help in the google group...

**Pull request closed without merging**
