### PR TITLE
Add NULL check in ensure_utf8

### PR DESCRIPTION
**Pull request by tiz314**
## Proposed Changes

Added check to verify that any utf8 string doesn't contain a NULL character, which is not allowed by the MQTT standard. This PR fixes the issue #2355.

This change is applied to both `ensure_utf8` functions in `vmq_parser.erl` and `vmq_parser_mqtt5.erl`

## Types of Changes

- [x] Bugfix (non-breaking change which fixes issue #2355 )
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation (correction or otherwise)
- [ ] Cosmetics (whitespace, styles...)
- [ ] DevOps (Build scripts, pipelines...)

## Checklist

- [x] I have read the [CODE_OF_CONDUCT.md](https://github.com/vernemq/vernemq/blob/main/CODE_OF_CONDUCT.md) document
- [x] All tests pass locally with my changes
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation (if needed)
- [x] Any dependent changes have been merged and published in related repositories
- [ ] I have updated changelog (At the bottom of the release version)
- [x] I have squashed all my commits into one before merging

### CODE REVIEW

**Comment by ioolkos** [comment]
@tiz314 Thanks!
I wonder whether we want to add a test case for this, where we'd generate a Connect packet with something like `gen_connect(<<0>>, [])`.
Also, I suppose NULL is forbidden for the MQTT username and any other UTF-8 strings here we use `ensure_utf8` as well), but I haven't yet looked into that.

**Comment by tiz314** [comment]
Of course! Following the [standard](https://docs.oasis-open.org/mqtt/mqtt/v5.0/mqtt-v5.0.pdf) it says that no UTF-8 encoded string are allowed to contain U+0000, so we should check every field in every possible MQTT packet type and add a check on them if the standard says it is processed as a string. 

As regards the test case, if you give me a go I can add a connect test in `vmq_server/test`

**Comment by ioolkos** [comment]
Adding a test to the vmq_server connect suite is great!
A previous commit by @mths1 added the UTF-8 verification for Username and Topic as well.

**Comment by tiz314** [comment]
I'm quite struggling with the development of the test case. Do you use common test? Which tool do you use to run it? I tried with rebar3 but it gives me errors about files not found, such as:

```
vmq_commons/src/vmq_types_common.hrl:{3,14}: can't find include lib "vernemq_dev/include/vernemq_dev.hrl"; Make sure vernemq_dev is in your app file's 'applications' list

vmq_commons/src/vmq_types_mqtt.hrl:{1,14}: can't find include lib "vernemq_dev/include/vernemq_dev.hrl"; Make sure vernemq_dev is in your app file's 'applications' list

vmq_commons/src/vmq_types_mqtt5.hrl:{1,14}: can't find include lib "vernemq_dev/include/vernemq_dev.hrl"; Make sure vernemq_dev is in your app file's 'applications' list
```

**Comment by ioolkos** [comment]
@tiz314 Here's how to proceed.
- In the vernemq dir, run `make rel` so that you have a default build (this will create `default` build in the `_build dir`)
- Run the full common test suites with `rebar3 ct`
- Alternatively, run a single test suite only with something like  `rebar3 ct --suite apps/vmq_webhooks/test/vmq_webhooks_SUITE.erl` (if you want, you can even just run single test cases)

Running any command with `rebar3 ct` will create a `test` build in the `_build` dir. In the `test` dir, you'll also have logs for your test runs. You'll also see HTTP files which you can open in a browser.

**Comment by tiz314** [comment]
I pushed a first version of the test case but I'm having some serious difficulties in catching the patched parser exception that gets raised when sending the null char, making the test always pass. 

First time with this kind of tech :(

**Comment by ioolkos** [comment]
@tiz314 Thanks for your effort, much appreciated. I'll look into the test case.

**Pull request merged**
