### PR TITLE
feat: change mongodb-erlang dep to use emqx fork

### PR DESCRIPTION
**Pull request by Climax777**
## Proposed Changes

Move the mongodb-erlang driver to the emqx fork. This supports the modern wire protocol from MongoDB 6 onwards.

## Types of Changes

- [x] Bugfix (non-breaking change which fixes issue #2357)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation (correction or otherwise)
- [ ] Cosmetics (whitespace, styles...)
- [ ] DevOps (Build scripts, pipelines...)

## Checklist
- [x] I have read the [CODE_OF_CONDUCT.md](https://github.com/vernemq/vernemq/blob/main/CODE_OF_CONDUCT.md) document
- [ ] All tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if needed)
- [ ] Any dependent changes have been merged and published in related repositories
- [ ] I have updated changelog (At the bottom of the release version)
- [ ] I have squashed all my commits into one before merging

### CODE REVIEW

**Comment by Climax777** [comment]
I'm happy to help with testing if you can guide me. I'm not well-versed in the Erlang ecosystem.

**Comment by ioolkos** [comment]
@Climax777 Thanks, the most important thing is to do some actual functional tests with the running plugin against your MongoDB instance.

**Comment by Climax777** [comment]
> @Climax777 Thanks, the most important thing is to do some actual functional tests with the running plugin against your MongoDB instance.

I've successfully authenticated with the new mongo plugin. I haven't exhaustively tested it though, for example with certs etc.

**Comment by Climax777** [comment]
Im not sure why the CI/CD pipeline failed, since no code was actually changed. I also couldn't see any unit tests for mongo as part of the default suite

**Review by ioolkos — APPROVED** [review]

**Pull request merged**
