### PR TITLE
Bump rebar3

### PR DESCRIPTION
**Pull request by varnerac**
## Proposed Changes

Bump `rebar3`

## Types of Changes

What types of changes does your code introduce to this project?
_Put an `x` in the boxes that apply_

- [ ] Bugfix (non-breaking change which fixes issue #XXXX)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation (correction or otherwise)
- [ ] Cosmetics (whitespace, styles...)
- [x] DevOps (Build scripts, pipelines...)

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating
the PR. If you're unsure about any of them, don't hesitate to ask on the
mailing list. We're here to help! This is simply a reminder of what we are
going to look for before merging your code._

- [x] I have read the `CODE_OF_CONDUCT.md` document
- [x] All tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if needed)
- [ ] Any dependent changes have been merged and published in related repositories
- [ ] I have updated changelog (At the bottom of the release version)
- [ ] I have squashed all my commits into one before merging

## Further Comments

My editor uses a recent version of rebar3 and always clobbers the lock file. I don't know if other folks are running into this or not.

### CODE REVIEW

**Comment by varnerac** [comment]
I'm pretty sure that 23.0.1 matrix fail is just a timing thing that shows up in CI.

**Comment by ioolkos** [comment]
Yeah, always timing :) I need rebar3 to work with my internal builds, that's why I don't merge this right away. I'll make sure of that.

**Comment by varnerac** [comment]
For what it's worth, I've verified that the `release` and `tar` targets complete with no errors. I haven't done smoke tests on the results.

**Comment by varnerac** [comment]
Closing since this is covered by https://github.com/vernemq/vernemq/pull/1737

**Pull request closed without merging**
