### PR TITLE
Collect metrics on webhook calls.

### PR DESCRIPTION
**Pull request by varnerac**
## Proposed Changes

Collect metrics per webhook type.

## Types of Changes

What types of changes does your code introduce to this project?
_Put an `x` in the boxes that apply_

- [ ] Bugfix (non-breaking change which fixes issue #XXXX)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation (correction or otherwise)
- [ ] Cosmetics (whitespace, styles...)
- [ ] DevOps (Build scripts, pipelines...)

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating
the PR. If you're unsure about any of them, don't hesitate to ask on the
mailing list. We're here to help! This is simply a reminder of what we are
going to look for before merging your code._

- [x] I have read the `CODE_OF_CONDUCT.md` document
- [x] All tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation (if needed)
- [x] Any dependent changes have been merged and published in related repositories
- [x] I have updated changelog (At the bottom of the release version)
- [x] I have squashed all my commits into one before merging

## Further Comments

I ran the webhooks suite and dialyzer. They pass. I haven't run the full VMQ suite because of clique issues.

### CODE REVIEW

**Comment by varnerac** [comment]
This isn't ready to merge yet. However, I wanted to post what I have to see if this is the right approach. It addresses https://github.com/vernemq/vernemq/issues/1915

**Comment by varnerac** [comment]
@ioolkos I think I should change this, and just add the webhook metrics here: https://github.com/vernemq/vernemq/blob/master/apps/vmq_server/src/vmq_metrics.erl#L681

It kind of conflates the `vmq_server` and `vmq_webhooks` model. I could also initialize all webhook metrics on VMQ web hooks startup. My initial strategy was to initialize the metrics on demand, because I wanted to a metric per webhook name (vs webhook "type"). The metrics system isn't really built for dynamically named metrics. So, I think the best route is to statically initialize the webhooks counters in the counters definition function in vmc_metrics. I'll have to leak the webhooks module in because of [met2idx](https://github.com/vernemq/vernemq/blob/master/apps/vmq_server/src/vmq_metrics.erl#L1161).

**Comment by ioolkos** [comment]
@varnerac thanks, one thing unclear to me: did you try to use a `vmq_metrics_mfa` (as, for example, in the bridge plugin or SWC plugin) and found specific reasons against it?
The simplicity of the `vmq_metrics_mfa` approach let's you just export a `metrics/0` function from any custom metrics module, and it'd only be enabled when the plugin is active.
Have you found this too rigid for the Webhooks case?

**Comment by varnerac** [comment]
@ioolkos I think the vmq_metrics_mfa is probably a better approach. I'll work on that.

**Comment by varnerac** [comment]
@ioolkos This one use the metrics MFA callback

**Comment by ioolkos** [comment]
@varnerac allright, thanks, looks good.

**Review by ioolkos — APPROVED** [review]

**Comment by ioolkos** [comment]
This broke tests apparently:
```
rebar3 ct
[...]
===> Compiling apps/vmq_server/test/vmq_publish_SUITE.erl failed
apps/vmq_server/test/vmq_publish_SUITE.erl:8:10: can't find include file "../src/vmq_metrics.hrl"

apps/vmq_server/test/vmq_publish_SUITE.erl:742:19: record metric_def undefined
``

**Comment by varnerac** [comment]
I'll patch

**Pull request merged**
