### PR TITLE
WIP: Add OSX CI

### PR DESCRIPTION
**Pull request by codeadict**
## Proposed Changes

Adds OSX to the CI builds so we catch when things break on this platform. 

## Types of Changes

What types of changes does your code introduce to this project?
_Put an `x` in the boxes that apply_

- [x] DevOps (Build scripts, pipelines...)

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating
the PR. If you're unsure about any of them, don't hesitate to ask on the
mailing list. We're here to help! This is simply a reminder of what we are
going to look for before merging your code._

- [x] I have read the `CODE_OF_CONDUCT.md` document
- [x] All tests pass locally with my changes
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation (if needed)
- [x] Any dependent changes have been merged and published in related repositories
- [ ] I have updated changelog (At the bottom of the release version)
- [ ] I have squashed all my commits into one before merging

## Further Comments

With many developers using OSX, thought was good to support it in our builds and as a test env for contributors not having a mac. The plan is to support the last 2 OSX versions. Still only one added but tests are passing. Maybe Windows is next :P. This also opens the possibility to generate OSX releases that could be used from Homebrew, adding a really simple experience for mac users.

### CODE REVIEW

**Comment by codeadict** [comment]
@ioolkos ^^

**Comment by ioolkos** [comment]
@codeadict great work :)

**Comment by varnerac** [comment]
This may be overcome by events, given https://github.com/vernemq/vernemq/pull/1715

**Comment by varnerac** [comment]
Can you close this based on https://github.com/vernemq/vernemq/pull/1715?

**Comment by ioolkos** [comment]
@varnerac @codeadict great stuff, thanks to both of you! closing as requested, in view of #1715

**Pull request closed without merging**
