### PR TITLE
Fix rpc timeout

### PR DESCRIPTION
**Pull request by scazzumvivendi**
## Proposed Changes

Please describe the big picture of your changes here to communicate to the
VerneMQ team why we should accept this pull request. If it fixes a bug or
resolves a feature request, be sure to link to that issue.

## Types of Changes

What types of changes does your code introduce to this project?
_Put an `x` in the boxes that apply_

- [X] Bugfix (non-breaking change which fixes issue #1412)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation (correction or otherwise)
- [ ] Cosmetics (whitespace, styles...)
- [ ] DevOps (Build scripts, pipelines...)

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating
the PR. If you're unsure about any of them, don't hesitate to ask on the
mailing list. We're here to help! This is simply a reminder of what we are
going to look for before merging your code._

- [X] I have read the `CODE_OF_CONDUCT.md` document
- [X] All tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if needed)
- [X] Any dependent changes have been merged and published in related repositories
- [ ] I have updated changelog (At the bottom of the release version)
- [ ] I have squashed all my commits into one before merging

## Further Comments

If this is a relatively large or complex change, kick off the discussion by
explaining why you chose the solution you did and what alternatives you
considered, etc.

### CODE REVIEW

**Comment by ioolkos** [comment]
@scazzumvivendi Thanks! can you explain, though: why does switching `sh` to `bash` fix a timeout? what OS are you on?

**Comment by scazzumvivendi** [comment]
@ioolkos the switch is needed for the change in the other commit, i.e. from 
```
case $1 in
```
to
```
ARG=($1)
case $ARG in
```
so that in the EC2 machine $1 is interpreted as the first parameter, and not as all the parameters. I don't know how to pinpoint this, but it works and it doesn't introduce regressions (that I am aware of).

**Comment by ioolkos** [comment]
@scazzumvivendi by the way: for what VerneMQ version (and self-compiled or subscription binary?) do you see this RPC timeout?
In general, I think it's best to keep the shell at `sh` which links to the system default, but I wondered what you actually use.

**Comment by scazzumvivendi** [comment]
I'm using version 1.12.1 self-compiled, and installed on an Amazon Linux (EC2) machine.

It's OK if you leave this hanging and not merged on master, as it can be simply patched if anyone has this issue (which, I iterate, is caused by bash on my EC2 instance, and not by VerneMQ itself).

**Comment by ioolkos** [comment]
@scazzumvivendi got, it, let's do it like that. I think we also change to bash in the package builds. Thanks for sharing your insights, in any case, I wasn't aware about this on EC2!

**Comment by mths1** [comment]
I was also running into this problem. The root cause is the "check_user" function, as can be easiliy demonstrated. Just add a echo $1 before and after the check_user

echo "a $1"
# Make sure the user running this script is the owner and/or su to that user
check_user "$@"
echo "b $1"

and also a 

        echo "INFINITY"
        $NODETOOL rpc_infinity vmq_server_cli command $SCRIPT $@;;
    *)
        echo "NON INFINITY"

you'll see that when you run the script with the vernemq user everything works smooth $1 is "trace" as expected, and then you will see INFINITY. If the check_user functions does a su the script is called again, but due to some escaping $1 is now trace client client_id and this you'll see NON INFINITY. A quick fix would be to change 
case $1 in "trace"
to 
case $1 in trace*  

or look deeper into what check_user does. This is not related to EC2 or something, I can reproduce this on a local machine with both Ubuntu and RHEL.

**Comment by mths1** [comment]
Changing

`exec su - $RUNNER_USER -s $RUNNER_SCRIPT_DIR/$RUNNER_SCRIPT -- "$ESCAPED_ARGS"`
to
`exec su - $RUNNER_USER -s $RUNNER_SCRIPT_DIR/$RUNNER_SCRIPT -- $ESCAPED_ARGS`

in env.sh should also fix the issue (and is actually the real root cause). The parantheses cause all arguments to be passed as one. No idea about what side effects that might cause, though, given that that code has been there for a while.

**Comment by ioolkos** [comment]
@mths1 okay, thanks for analyzing this! I'll have to dig into this and check why we wanted to pass all arguments as one.

**Pull request closed without merging**
