### PR TITLE
Webhooks HTTPS Enhancements

### PR DESCRIPTION
**Pull request by varnerac**
This WIP PR improves HTTPS in web hooks. I just copied the test certs from `vmq_server`, but that's ugly. Can I move the test certs to the top-level of the project since I'll need them in these tests and in `vmq_server` tests?

Adds HTTPS-specific options to the webhooks module and tests. Allows
users to specify a custom CA and verification options. Allows hooks
to authenticate to endpoints with client certificates.

Adds PEM validation to the vmq_server and vmq_webhooks schemas.

## Proposed Changes

Improve HTTPS support in webhooks. Validate certificate files in the server and webhooks schemas.

## Types of Changes

What types of changes does your code introduce to this project?
_Put an `x` in the boxes that apply_

- [ ] Bugfix (non-breaking change which fixes issue #XXXX)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [X] Documentation (correction or otherwise)
- [X] Cosmetics (whitespace, styles...)
- [ ] DevOps (Build scripts, pipelines...)

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating
the PR. If you're unsure about any of them, don't hesitate to ask on the
mailing list. We're here to help! This is simply a reminder of what we are
going to look for before merging your code._

- [x] I have read the `CODE_OF_CONDUCT.md` document
- [x] All tests pass locally with my changes
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation (if needed)
- [x] Any dependent changes have been merged and published in related repositories
- [x] I have updated changelog (At the bottom of the release version)
- [x] I have squashed all my commits into one before merging

## Further Comments

If this is a relatively large or complex change, kick off the discussion by
explaining why you chose the solution you did and what alternatives you
considered, etc.

### CODE REVIEW

**Comment by ioolkos** [comment]
@varnerac looking great so far! :+1: 
Guess moving test certs to toplevel is somwhat 'ugly' too :) but I'm fine with it. As long as it's clear that they're just that, a bunch of certs only used in testing.

**Comment by varnerac** [comment]
I may just leave a few in a test directory. While I am in here, I am refactoring some of the test code to pull artifacts like "dummy files" from `foo_SUITE_data` directories using the CT macros.

**Comment by varnerac** [comment]
If CI is clean, this ready for review

**Comment by varnerac** [comment]
Meh. I've somehow bumped `rebar.lock` to a new version. I probably forget to hit `./rebar3 ct`. I am gonna revert that.

**Comment by varnerac** [comment]
Ok. Reverted the `rebar.lock`. We should be good to go.

**Comment by ioolkos** [comment]
@varnerac Do the WebHook tests run ok, locally? they failed for all Erlang versions in last build, but I can't restart the build on Travis (out of build points there)

**Comment by varnerac** [comment]
They do locally. Both the webhooks and server schema suite should be checked, because I added PEM validation to the server schema too.

```
varnerac@Drews-MacBook-Pro vernemq % asdf current erlang
erlang          23.2.1          /Users/varnerac/vernemq/.tool-versions
varnerac@Drews-MacBook-Pro vernemq % ./rebar3 ct --suite apps/vmq_webhooks/test/vmq_webhooks_SUITE
===> Rebar3 detected a lock file from a newer version. It will be loaded in compatibility mode, but important information may be missing or lost. It is recommended to upgrade Rebar3.
===> Verifying dependencies...
===> Compiling vmq_ql
===> Running neotoma...
===> Compiling vmq_plugin
===> Compiling vmq_commons
===> Compiling vmq_server
===> Compiling vmq_webhooks
===> Compiling vmq_swc
===> Compiling vmq_acl
===> Compiling vmq_plumtree
===> Compiling vmq_generic_msg_store
===> Compiling vmq_passwd
cc   -L/usr/local/opt/openssl/lib -I/usr/local/opt/openssl/include vmq_passwd.c -lcrypto -o ../priv/vmq_passwd
===> Compiling vmq_mqtt5_demo_plugin
===> Compiling vmq_pulse
===> Compiling vmq_bridge
===> Compiling vmq_diversity
===> Running Common Test suites...
%%% vmq_webhooks_SUITE: ......................................[os_mon] memory supervisor port (memsup): Erlang has closed
[os_mon] cpu supervisor port (cpu_sup): Erlang has closed

All 38 tests passed.
varnerac@Drews-MacBook-Pro vernemq % ./rebar3 ct --suite apps/vmq_server/test/vmq_schema_SUITE
===> Rebar3 detected a lock file from a newer version. It will be loaded in compatibility mode, but important information may be missing or lost. It is recommended to upgrade Rebar3.
===> Verifying dependencies...
===> Compiling vmq_ql
===> Running neotoma...
===> Compiling vmq_plugin
===> Compiling vmq_commons
===> Compiling vmq_server
===> Compiling vmq_webhooks
===> Compiling vmq_swc
===> Compiling vmq_acl
===> Compiling vmq_plumtree
===> Compiling vmq_generic_msg_store
===> Compiling vmq_passwd
cc   -L/usr/local/opt/openssl/lib -I/usr/local/opt/openssl/include vmq_passwd.c -lcrypto -o ../priv/vmq_passwd
===> Compiling vmq_mqtt5_demo_plugin
===> Compiling vmq_pulse
===> Compiling vmq_bridge
===> Compiling vmq_diversity
===> Running Common Test suites...
%%% vmq_schema_SUITE: .........
All 9 tests passed.
```

**Comment by varnerac** [comment]
I think the `rebar.lock` issue comes from the Erlang Language Server (LS) in my VS Code.

**Comment by ioolkos** [comment]
@varnerac Great, I'm merging this!

**Pull request merged**
