### PR TITLE
Add macOS to CI

### PR DESCRIPTION
**Pull request by varnerac**
## Proposed Changes

Add a macOS target to GitHub

## Types of Changes

What types of changes does your code introduce to this project?
_Put an `x` in the boxes that apply_

- [ ] Bugfix (non-breaking change which fixes issue #XXXX)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation (correction or otherwise)
- [ ] Cosmetics (whitespace, styles...)
- [x] DevOps (Build scripts, pipelines...)

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating
the PR. If you're unsure about any of them, don't hesitate to ask on the
mailing list. We're here to help! This is simply a reminder of what we are
going to look for before merging your code._

- [x] I have read the `CODE_OF_CONDUCT.md` document
- [x] All tests pass locally with my changes
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation (if needed)
- [x] Any dependent changes have been merged and published in related repositories
- [x] I have updated changelog (At the bottom of the release version)
- [x] I have squashed all my commits into one before merging

## Further Comments

This uses GitHub Actions to handle the work in https://github.com/vernemq/vernemq/pull/1631, which seems to be abandoned.

### CODE REVIEW

**Comment by ioolkos** [comment]
Hm, I don't see which are the failing tests for the MacOS build.

**Comment by varnerac** [comment]
It’s only one test. I’m still troubleshooting it. 

```
%%% vmq_metrics_SUITE ==> {{badmatch,{error,timeout}},
745
 [{vmq_metrics_SUITE,simple_systree_test,1,
746
                     [{file,"/Users/runner/work/vernemq/vernemq/apps/vmq_server/test/vmq_metrics_SUITE.erl"},
747
                      {line,59}]},
748
  {test_server,ts_tc,3,[{file,"test_server.erl"},{line,1754}]},
749
  {test_server,run_test_case_eval1,6,[{file,"test_server.erl"},{line,1263}]},
750
  {test_server,run_test_case_eval,9,[{file,"test_server.erl"},{line,1195}]}]}
  ```

**Comment by ioolkos** [comment]
I see, timing issues again. If this runs locally but is non-deterministic in GA, we can always skip the test.

**Comment by varnerac** [comment]
It passes now. I had to set an explicit timeout vs. a default timeout, but it works.

**Pull request merged**
