### PR TITLE
Safe binary to term

### PR DESCRIPTION
**Pull request by varnerac**
## Proposed Changes

Use the `safe` option in `binary_to_term` calls for SWC. Validate that MQTT topics are valid UTF8 strings in the parser. UTF8 validation is a breaking change, but it is required by the MQTT 3.1.1 and 5.0 specifications.

## Types of Changes

What types of changes does your code introduce to this project?
_Put an `x` in the boxes that apply_

- [x] Bugfix (non-breaking change which fixes non-compliance with MQTT specs)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation (correction or otherwise)
- [ ] Cosmetics (whitespace, styles...)
- [ ] DevOps (Build scripts, pipelines...)

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating
the PR. If you're unsure about any of them, don't hesitate to ask on the
mailing list. We're here to help! This is simply a reminder of what we are
going to look for before merging your code._

- [x] I have read the `CODE_OF_CONDUCT.md` document
- [x] All tests pass locally with my changes
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation (if needed)
- [x] Any dependent changes have been merged and published in related repositories
- [ ] I have updated changelog (At the bottom of the release version)
- [x] I have squashed all my commits into one before merging

### CODE REVIEW

**Comment by ioolkos** [comment]
Great stuff, thank you. Will review as quickly as possible. Those topic tests really call for property based testing... :)

**Comment by varnerac** [comment]
Yeah. I’d agree on the property-based tests. I’m just not sure what properties would have to hold.

**Comment by ioolkos** [comment]
Good point, maybe I can come up with some. Certainly not meant as a requirement for this PR.

**Review by ioolkos — APPROVED** [review]

**Comment by ioolkos** [comment]
Looks good. 
Let's see whether we encounter any "bad arguments" from those safe binary_to_terms, then we'd know we created hidden atoms before :)

**Comment by varnerac** [comment]
Yeah. If someone does an hot upgrade, a new record name could easily cause this. I’ll test some more this coming week.

**Pull request merged**
