### PR TITLE
Log peer information on authentication failures

### LINKED ISSUE #931: Adapt Logs to be useful for fail2ban
I guess at least for failed authentications.

### PR DESCRIPTION
**Pull request by larshesel**
Fixes #931

### CODE REVIEW

**Comment by larshesel** [comment]
Fixed dialyzer issue (thanks, dialyzer, that was a real bug!)

**Comment by larshesel** [comment]
> Shouldn't we use the IP:Port format in the logs?

That was my initial thought, but how would you format the IPv6 strings with ports. It seems that in URLS you'd do `[2a02:120b:7fd:1060:9eb6:d0ff:fed0:232f]:12744`, but I'm not sure if it is really a standard. That's why I went with a space between the IP and port. If you think it better I'll change it to `IPv4:Port` and `[IPv6]:Port`.

**Comment by larshesel** [comment]
> If you think it better I'll change it to `IPv4:Port` and `[IPv6]:Port`.

You know what, I'll just do that... The other format annoyed me as well.

**Comment by dergraf** [comment]
good point.let's be pragmatic, what is the format that yields the easiest regex pattern. ;)

**Comment by larshesel** [comment]
> good point.let's be pragmatic, what is the format that yields the easiest regex pattern. ;)

I don't know, you tell me! :)

**Comment by larshesel** [comment]
Changed it to `IPv4:Port` and `[IPv6]:Port`.

**Pull request merged**
