### PR TITLE
Ensure_that_MQTT_v5_user_properties_are_stored_to_disk/DB_#1560

### PR DESCRIPTION
**Pull request by steve999lee**
…age_#1560

## Proposed Changes

Changes to vmq_generic_msg_store_utils.erl to read and write properties from the store. Payload and Properties are combined into a single tuple before writing. 

The change is backwards compatible in case the store contains messages persisted by an earlier version 

I modified an existing test so that test messages contain properties

## Types of Changes

What types of changes does your code introduce to this project?
_Put an `x` in the boxes that apply_

- [x ] Bugfix (non-breaking change which fixes issue #1560 )
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation (correction or otherwise)
- [ ] Cosmetics (whitespace, styles...)
- [ ] DevOps (Build scripts, pipelines...)

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating
the PR. If you're unsure about any of them, don't hesitate to ask on the
mailing list. We're here to help! This is simply a reminder of what we are
going to look for before merging your code._

- [x ] I have read the `CODE_OF_CONDUCT.md` document
- [x ] All tests pass locally with my changes
- [x ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if needed)
- [ ] Any dependent changes have been merged and published in related repositories
- [ ] I have updated changelog (At the bottom of the release version)
- [x ] I have squashed all my commits into one before merging

## Further Comments

This is my first attempt at erlang code so probably the style isnt great

### CODE REVIEW

**Comment by ioolkos** [comment]
@steve999lee thanks! will review asap. The build currently fails due to type errors. (if you want to check & fix this locally, run `./rebar3 dialyzer`).
Protocol backward compatibility is vital, obviously, but you seem to have checked for that. If this proves good enough, it'll be a great contribution! :)

**Comment by ioolkos** [comment]
Locally, I have 2 errors in the `vmq_publish SUITE`,
one for `mqttv4.pattern_matching_test`, one for `mqttv4.not_allowed_publish_close_qos2_mqtt_3_1_1`, so I need to investigate those.

**Comment by steve999lee** [comment]
Ah - I only ran the ct tests - I guess I have to run dialyzer and eunit as well

**Comment by ioolkos** [comment]
@steve999lee `./rebar3 ct` will run all the tests. `./rebar3 dialyzer` has to be run separately.
Apparently, for you all the Common Tests pass?

**Comment by steve999lee** [comment]
@ioolkos - I think so

Skipped 14 (14, 0) tests. Passed 389 tests.

**Comment by steve999lee** [comment]
I can fix it such that dialyzer and ct (and my tests) pass by changing the type to allow either a payload() or a tuple() 
`-type p_msg_val_pre() :: {routing_key(), payload() | tuple()}.`

Or perhaps there is a better way?

**Review by ioolkos — APPROVED** [review]

**Comment by ioolkos** [comment]
@steve999lee thanks again for your effort, I hope this simple approach can take us far. If you test this on MQTT v5 level, can you observe behaviour and semantics a little bit? (like: are message TTL respected, do all properties arrive at subscriber, do we potentially need to filter out properties at some point, etc.)

**Comment by steve999lee** [comment]
@ioolkos - yes we plan to use MQTT5 for our messaging framework and to make use of properties and TTL so we are thoroughly testing these behaviours. I don't have a use case for filtering out properties though.

**Pull request merged**
