### PR TITLE
Enable the Bridge client to connect to Inet6 MQTT endpoints

### PR DESCRIPTION
**Pull request by ioolkos**
Doc:
Introduces new vmq_bridge config settings:

`vmq_bridge.tcp.default.inet_version = inet|inet6`
`vmq_bridge.ssl.default.inet_version = inet|inet6`

with `default` being an arbitrary bridge name, informing `default` that the other bridge endpoint to contact is an IPv4 or IPv6 endpoint.

### CODE REVIEW

**Comment by mrceyhun** [comment]
Hi @ioolkos , many thanks for this PR. Are you planning to make any pre-release or RC including this changes? It would be great to have.

**Comment by mrceyhun** [comment]
One more question: if a new release will take time, do you think we can cherry-pick this commit to a release `1.12.4` ( or `1.13`) without having any issue?

**Comment by ioolkos** [comment]
@mrceyhun this will be part of the final release of 2.0, yes. It'd be great if someone can test the feature with their use case.

**Comment by mrceyhun** [comment]
Thanks @ioolkos . Do you think it is ok to cherry-pick this commit to the `1.13`(or `1.12.4`) release? If so, we can test and report our use-case of this PR.

**Comment by ioolkos** [comment]
@mrceyhun Maybe, but I cannot review the commit history right now to *guarantee* it to you.

**Comment by mrceyhun** [comment]
Got it, thank you!

**Pull request merged**
