### PR TITLE
Fix handling of WebSocket protocols

### PR DESCRIPTION
**Pull request by varnerac**
Correctly handles mutliple values in the `sec_websocket_protocol` HTTP
header.

## Proposed Changes

Fixes a broken implementation of WebSockets protocols in VerneMQ. It now properly handles multiple protocols specified in the same request.

## Types of Changes

What types of changes does your code introduce to this project?

- [X] Bugfix (non-breaking change which fixes issue #1620)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation (correction or otherwise)
- [ ] Cosmetics (whitespace, styles...)
- [ ] DevOps (Build scripts, pipelines...)

## Checklist

- [X] I have read the `CODE_OF_CONDUCT.md` document
- [X] All tests pass locally with my changes
- [X] I have added tests that prove my fix is effective or that my feature works
- [X] I have added necessary documentation (if needed)
- [X] Any dependent changes have been merged and published in related repositories
- [X] I have updated changelog (At the bottom of the release version)
- [X] I have squashed all my commits into one before merging

## Further Comments

This changes the behavior of `packet:do_client_connect/3` to return the error if `Transport:connect/4` fails instead of crashing. This was necessary to enable a more robust test suite for the WebSocket protocol functionality. This change seemed reasonable to me.

### CODE REVIEW

**Review by ioolkos — APPROVED** [review]
Okay, thanks!

**Comment by ioolkos** [comment]
@varnerac want to merge this but the usual "Update Branch" button is missing here for out-of-date base branches. 
Don't know why.
Maybe you have to merge master again?

**Comment by varnerac** [comment]
I see. I’ll rebase it.

**Comment by varnerac** [comment]
A test is failing in CI, but I don't think it has anything to do with my changes.

**Comment by ioolkos** [comment]
@varnerac jep, test failing is unrelated. This is just Travis as usual.

Fixes https://github.com/vernemq/vernemq/issues/1620

**Pull request merged**
