### PR TITLE
Specify named curves

### PR DESCRIPTION
**Pull request by varnerac**
Allows users to specify a list of named curves for elliptic curve
cryptography.

## Proposed Changes

Allows specification of allowed ECC named curves in the configuration.

## Types of Changes

What types of changes does your code introduce to this project?
_Put an `x` in the boxes that apply_

- [X] Bugfix (non-breaking change which fixes issue #1594)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation (correction or otherwise)
- [ ] Cosmetics (whitespace, styles...)
- [ ] DevOps (Build scripts, pipelines...)

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating
the PR. If you're unsure about any of them, don't hesitate to ask on the
mailing list. We're here to help! This is simply a reminder of what we are
going to look for before merging your code._

- [X] I have read the `CODE_OF_CONDUCT.md` document
- [X] All tests pass locally with my changes
- [X] I have added tests that prove my fix is effective or that my feature works
- [X] I have added necessary documentation (if needed)
- [ ] Any dependent changes have been merged and published in related repositories
- [X] I have updated changelog (At the bottom of the release version)
- [X] I have squashed all my commits into one before merging

### CODE REVIEW

**Comment by ioolkos** [comment]
@varnerac great stuff, thanks. One of the builds fails, I think just the usual Travis issues, so no blocker.
I'm going to go through it and extract a little bit of documentation from it.

**Comment by varnerac** [comment]
There is an issue where some of the "prime" curves slip through. I am pretty sure this is an Erlang `ssl` issue. I'll take a look at it. I don't think it's something we can fix in VerneMQ.

**Comment by varnerac** [comment]
I just fixed a bug where the comments showed the format as:

```
sect571k1:secp521r1:brainpoolP512r1
```

Corrected it to:

```
[sect571k1,secp521r1,brainpoolP512r1]
```

When I did, my editor removed trailing space on the `.schema` file. Let me know if you want to add the trailing space back in.

**Comment by ioolkos** [comment]
> When I did, my editor removed trailing space on the `.schema` file. Let me know if you want to add the trailing space back in.

Thanks, no need to put trailing spaces back in.

**Review by ioolkos — APPROVED** [review]

**Pull request merged**
