### PR TITLE
Prepare for Erlang/OTP 22

### PR DESCRIPTION
**Pull request by codeadict**
Addresses: #1196

Comes with https://github.com/vernemq/plumtree/pull/24

### CODE REVIEW

**Comment by larshesel** [comment]
Thanks for the PR much appreciated :) I merged vernemq/plumtree#24, can you fixup the reference there, and squash the commits for each of the three fixes (one commit per changelog entry)?

**Comment by larshesel** [comment]
I just merged #1211, so I guess this should just be rebased and squashed.

**Comment by codeadict** [comment]
Sure, I will rebase an squash when I reach my computer.

**Comment by codeadict** [comment]
Squashed and re-based, ready to merge :crossed_fingers:

**Pull request merged**
