### PR TITLE
Add support for Redis user

### PR DESCRIPTION
**Pull request by goldyfruit**
## Proposed Changes

_PR is related to issue https://github.com/vernemq/vernemq/issues/2110_

Adding support for Redis "user" allows the use of Redis with ACL to
leverage some security feature such as:

  - Different user than "default"
  - Different password
  - Level of permissions
  - Key patterns

## Types of Changes

What types of changes does your code introduce to this project?
_Put an `x` in the boxes that apply_

- [x] Bugfix (non-breaking change which fixes issue #2110)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation (correction or otherwise)
- [ ] Cosmetics (whitespace, styles...)
- [ ] DevOps (Build scripts, pipelines...)

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating
the PR. If you're unsure about any of them, don't hesitate to ask on the
mailing list. We're here to help! This is simply a reminder of what we are
going to look for before merging your code._

- [x] I have read the [CODE_OF_CONDUCT.md](https://github.com/vernemq/vernemq/blob/main/CODE_OF_CONDUCT.md) document
- [x] All tests pass locally with my changes
- [x] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if needed)
- [x] Any dependent changes have been merged and published in related repositories
- [ ] I have updated changelog (At the bottom of the release version)
- [x] I have squashed all my commits into one before merging

### CODE REVIEW

**Comment by ioolkos** [comment]
@goldyfruit nice, thanks! could you add a line to the `changelog.md`?

Also (if you strive for perfection ;)... opening a quick PR against the vmq-docs master branch with a short description of the feature. Probably best in the Redis section of the "Auth with databases" chapter.

Have you made sure that the actual auth queries to Redis work? (i.e that new user would not be underprivileged for that, or anything similar).

**Review by codeadict — DISMISSED** [review]

**Review by ioolkos — CHANGES_REQUESTED** [review]
Just a small ask: please commit a line like the  following to `changelog.md`:
- Make Redis username configurable in vmq_diversity.

Thanks!

**Comment by goldyfruit** [comment]
> @goldyfruit nice, thanks! could you add a line to the `changelog.md`?

Done

> Also (if you strive for perfection ;)... opening a quick PR against the vmq-docs master branch with a short description of the feature. Probably best in the Redis section of the "Auth with databases" chapter.

I will.

> Have you made sure that the actual auth queries to Redis work? (i.e that new user would not be underprivileged for that, or anything similar).

All my tests were successful, I set the default Redis user to `default` _(according Redis documentation)_.

**Comment by ioolkos** [comment]
@goldyfruit Merging. Thanks again!

**Comment by goldyfruit** [comment]
> @goldyfruit Merging. Thanks again!

Awesome, thanks!

**Comment by ioolkos** [comment]
@mths1 oh, interesting. So Redis 5 does not have that username option? 
cc @goldyfruit what is your take on this?

**Comment by ioolkos** [comment]
@goldyfruit Thanks for your info. We can fix this inline, I guess, with no need for a legacy option. When a user is not given (let's say 'undefined'), we return different opts in `vmq_diversity_redis`.

**Pull request merged**
