### PR TITLE
Feature/set mqtt connect timeout

### PR DESCRIPTION
**Pull request by joskwanten**
This is a fix for #735 and #824 to make the mqtt connection timeout configurable. The timeout is the time between setting up the TCP or TLS connection and sending the 'CONNECT' message. The timeout time can be specified by setting the mqtt_connect_timeout in the vernemq.conf configuration file. The default is still 5000ms.

### CODE REVIEW

**Comment by ioolkos** [comment]
@joskwanten thanks... did you actually encounter the mentioned issues, and this solves those?

**Comment by joskwanten** [comment]
@ioolkos we did encounter this problem in the past when we tested an NB-IoT modem and typing AT commands by hand in a terminal to establish a connection to an MQTT server and were concerned that this can actually happen in a production environment on constrained devices in combination with a slow network. Therefore we want to be able to tune this timeout parameter if needed. Besides in other brokers like HiveMQ this is also a configurable setting (no-connect-packet-idle-timeout-millis). I tested this PR for both TCP and SSL and it will close the connection from server side when no CONNECT is send from the client in the specified time.

**Comment by krisfremen** [comment]
@joskwanten recently encountered this issue as well. Thank you for the PR!

This would be a very welcome addition to VerneMQ!

**Comment by ioolkos** [comment]
@joskwanten could you add an entry to the changelog? then we're good to go, I think.

**Comment by codeadict** [comment]
This is awesome, tanks for it!

**Comment by ioolkos** [comment]
Huh, travis checks still pending?

**Pull request merged**
