### PR TITLE
Add PR template

### PR DESCRIPTION
**Pull request by codeadict**
This is just to open a discussion about contribution checklist and standards, we can polish this together.

### CODE REVIEW

**Comment by codeadict** [comment]
@larshesel @dergraf @ioolkos ^^

**Comment by dergraf** [comment]
good initiative. :) I'd change a few points, but haven't had time to write down my thoughts.

**Comment by codeadict** [comment]
Great!

**Comment by ioolkos** [comment]
Another forgotten PR. I'm going to merge this as this was @codeadict's initiative, we can always adapt. (I also created a general .github repo today, for any useful templates)

**Pull request merged**
