### PR TITLE
Centralize JSON encoding/decoding

### PR DESCRIPTION
**Pull request by codeadict**
## Proposed Changes

This PR abstracts JSON encoding/decoding in a common module, despite of
what library is used behind the scenes. This allows for easier refactoring
as well as switching the JSON library to a faster one with minimal effort.

With upcoming JSON logging that I'm working on it would probably make a difference
to have a library like jsone or thoas that are faster and more memory efficient than JSX.

## Types of Changes

What types of changes does your code introduce to this project?
_Put an `x` in the boxes that apply_

- [ ] Bugfix (non-breaking change which fixes issue #XXXX)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation (correction or otherwise)
- [ ] Cosmetics (whitespace, styles...)
- [ ] DevOps (Build scripts, pipelines...)

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating
the PR. If you're unsure about any of them, don't hesitate to ask on the
mailing list. We're here to help! This is simply a reminder of what we are
going to look for before merging your code._

- [x] I have read the `CODE_OF_CONDUCT.md` document
- [x] All tests pass locally with my changes
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation (if needed)
- [ ] Any dependent changes have been merged and published in related repositories
- [] I have updated changelog (At the bottom of the release version)
- [x] I have squashed all my commits into one before merging

## Further Comments

@ioolkos - I was thinking if we should add the shared JSON library to `vernemq_dev` to have a common JSON library for plugin writers?

### CODE REVIEW

**Comment by ioolkos** [comment]
@codeadict thanks, a great idea & see the point with refactoring.
So far we have `vernemq_dev` dependency free; so I'd probably prefer not adding a JSON lib there too. (let me know if you see further benefits in it, though)

**Review by ioolkos — DISMISSED** [review]

**Comment by codeadict** [comment]
@ioolkos - looks like some MongoDB tests fail now due to deprecated commands in the Mongo Server and the library we use doesn't support them. We might need to pin CI to a specific mongo version until that is fixed in the library.

**Comment by codeadict** [comment]
Pushed the pinned version @ioolkos, here is the deprecation notice for MongoDB 6.0+ https://www.mongodb.com/docs/v6.0/release-notes/6.0-compatibility/#legacy-opcodes-removed

**Comment by codeadict** [comment]
Opened ticket on https://github.com/comtihon/mongodb-erlang/issues/254

**Pull request merged**
