### PR TITLE
[WIP] Revert MongoDB pool init change

### PR DESCRIPTION
**Pull request by varnerac**
Revert move from mc_worker:start_link/1 to mc_worker_api:connect/1.
Calling start_link/1 sets the MongoDB r_mode and w_mode.

## Proposed Changes

Please describe the big picture of your changes here to communicate to the
VerneMQ team why we should accept this pull request. If it fixes a bug or
resolves a feature request, be sure to link to that issue.

## Types of Changes

What types of changes does your code introduce to this project?
_Put an `x` in the boxes that apply_

- [x] Bugfix (non-breaking change which fixes issue #1821)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation (correction or otherwise)
- [ ] Cosmetics (whitespace, styles...)
- [ ] DevOps (Build scripts, pipelines...)

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating
the PR. If you're unsure about any of them, don't hesitate to ask on the
mailing list. We're here to help! This is simply a reminder of what we are
going to look for before merging your code._

- [x] I have read the `CODE_OF_CONDUCT.md` document
- [x] All tests pass locally with my changes
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation (if needed)
- [x] Any dependent changes have been merged and published in related repositories
- [x] I have updated changelog (At the bottom of the release version)
- [x] I have squashed all my commits into one before merging

## Further Comments

If this is a relatively large or complex change, kick off the discussion by
explaining why you chose the solution you did and what alternatives you
considered, etc.

### CODE REVIEW

**Review by ioolkos — APPROVED** [review]

**Comment by varnerac** [comment]
It's failing MongoDB in diversity tests. Gonna mark this WIP as I troubleshoot.

**Comment by varnerac** [comment]
works on my laptop:

```
===> Running Common Test suites...
%%% vmq_diversity_provider_SUITE: .......
All 7 tests passed.
```

**Comment by ioolkos** [comment]
@varnerac Thanks, let me know when this is fine to merge.

**Comment by varnerac** [comment]
Need to work on this fix.

**Pull request closed without merging**
