### PR TITLE
Compat OTP 24

### PR DESCRIPTION
**Pull request by manifest**
#1822 with disabled stacktrace.
It's still pointing to **rebar3_cuttlefish**'s master branch, assuming [this commit](https://github.com/vernemq/rebar3_cuttlefish/commit/29bb950282063bb60579a5d551755b108d912fb5) will be reverted first.

### CODE REVIEW

**Comment by ioolkos** [comment]
@manifest do you want to merge master into your branch, or do you want me to look into the merge conflicts?

**Comment by manifest** [comment]
I'll try to look into it. Something is broken after rebasing to the current master.

**Comment by manifest** [comment]
It compiles now. The `rebar.config` got updated, and I missed that `edown` was fixed [there](https://github.com/vernemq/vernemq/pull/1822/commits/765503b488f3664a541969003cf74493c5bacb8b#diff-54d206794bbd7299616a51ef468c2aa8a076534de1d98d1786b1ea5abe7776f0R27). I fixed its version in the same way.
@ioolkos

**Comment by ioolkos** [comment]
@manifest thanks... still seems to have issues for me (doesn't compile on OTP 22-24).
Can you do a full build on 24? (with rm'd _build directory)

**Comment by manifest** [comment]
I'm building this image with `--no-cache`, so `_build` shouldn't be an issue.
```dockerfile
FROM erlang:24-slim as build-stage

RUN apt update && apt install -y --no-install-recommends \
    ca-certificates \
    pkg-config \
    build-essential \
    libbsd-dev \
    libssl-dev \
    libcurl4-openssl-dev \
    libsnappy-dev \
    git \
    wget \
    curl

RUN git clone -q --branch compat_otp_24_cuttlefish https://github.com/manifest/vernemq.git
WORKDIR vernemq
RUN make rel
```
```bash
docker build -t mqtt-gateway-test . --no-cache
```

The only [difference between this PR and `compat_otp_24_cuttlefish`](https://github.com/manifest/vernemq/compare/c89d9de..f52e794) is a `rebar3_cuttlefish` version. In this PR it's still pointing to the `master` branch. Should I fix it to `4cf5e1c`?

**Comment by manifest** [comment]
[This one](https://github.com/vernemq/vernemq/pull/1879) should pass the tests.

**Comment by manifest** [comment]
The image compiles for OTP 21-24, but some tests are failing. I'm not sure what should be done about that.

**Comment by ioolkos** [comment]
@manifest don't worry about the test this time. Yes, it compiles on 22-24, but at least for 22 and 23 we seem to build invalid releases (ie. you can't start Verne). Surely related to rebar3, rebar3_cuttlefish
Haven't yet digged deeper.

**Pull request closed without merging**
