### PR TITLE
Updated luerl commit tag

### PR DESCRIPTION
**Pull request by B-1P**
## Proposed Changes

Please describe the big picture of your changes here to communicate to the
VerneMQ team why we should accept this pull request. If it fixes a bug or
resolves a feature request, be sure to link to that issue.

## Types of Changes

What types of changes does your code introduce to this project?
_Put an `x` in the boxes that apply_

- [X ] Bugfix (non-breaking change which fixes issue #XXXX)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation (correction or otherwise)
- [ ] Cosmetics (whitespace, styles...)
- [ ] DevOps (Build scripts, pipelines...)

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating
the PR. If you're unsure about any of them, don't hesitate to ask on the
mailing list. We're here to help! This is simply a reminder of what we are
going to look for before merging your code._

- [X] I have read the `CODE_OF_CONDUCT.md` document
- [X] All tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if needed)
- [ ] Any dependent changes have been merged and published in related repositories
- [ ] I have updated changelog (At the bottom of the release version)
- [x] I have squashed all my commits into one before merging

## Further Comments

Luerl tag version being referenced no longer exists causing the build to fail. This fix addresses that.

### CODE REVIEW

**Review by ioolkos — APPROVED** [review]
I think this is good. In the `rebar.conf` file of vmq_diversity we just pin Luerl to "develop" branch. Maybe we could change this to the tagged 1.0 release. Not too important, I guess.

Your branch is called "fixBuild", did this actually not work?

**Comment by sooslaca** [comment]
I just tested to add this over tag 1.12.1 and it's working. Thank you

**Comment by B-1P** [comment]
> Your branch is called "fixBuild", did this actually not work?

Yeah without this, the previous hash fails to build as it cannot be fetched / no longer in the repository.

**Comment by ioolkos** [comment]
@B-1P thanks!

**Pull request merged**
