### PR TITLE
Upgrade clique dependency to fix bug with empty kv params

### LINKED ISSUE #1401: Failed RPC using an empty client-id
### Environment

- VerneMQ Version: 1.10.0

### Expected behavior

I would expect the cli-client to warn me if i provide an empty client-id in the trace command.

```shell
vernemq@vernemq-0:~$ vmq-admin trace client client-id=
Please enter the id of the client you want to trace!
```

### Actual behaviour

```shell
vernemq@vernemq-0:~$ vmq-admin trace client client-id=
RPC to 'VerneMQ@vernemq-0.vernemq.messaging.svc.cluster.local' failed: {'EXIT',
                                                                        {function_clause,
                                                                         [{clique_error,
                                                                           format,
                                                                           ["vmq-admin",
                                                                            {error,
                                                                             {invalid_kv_arg,
                                                                              "client-id"}}],
                                                                           [{file,
                                                                             "/opt/vernemq/_build/default/lib/clique/src/clique_error.erl"},
                                                                            {line,
                                                                             29}]},
                                                                          {clique,
                                                                           print,
                                                                           3,
                                                                           [{file,
                                                                             "/opt/vernemq/_build/default/lib/clique/src/clique.erl"},
                                                                            {line,
                                                                             109}]},
                                                                          {clique,
                                                                           print,
                                                                           2,
                                                                           [{file,
                                                                             "/opt/vernemq/_build/default/lib/clique/src/clique.erl"},
                                                                            {line,
                                                                             92}]},
                                                                          {rpc,
                                                                           '-handle_call_call/6-fun-0-',
                                                                           5,
                                                                           [{file,
                                                                             "rpc.erl"},
                                                                            {line,
                                                                             197}]}]}}
```

### PR DESCRIPTION
**Pull request by codeadict**
Fixes #1401 

Perhaps a good idea would be to create a tag in the `vernemq/clique` repo instead of using the develop-3.0 branch. Thoughts @ioolkos

### CODE REVIEW

**Comment by ioolkos** [comment]
created a tag (release): https://github.com/vernemq/clique/releases/tag/v0.3.11-verne

**Comment by codeadict** [comment]
Still fixing some tests here

**Comment by ioolkos** [comment]
@codeadict please let me know in case I can do/test/help something here

**Comment by codeadict** [comment]
Hey @ioolkos , some things changed in the library that break tests, I was over the problem and fixing it but have been sick from allergies the last 2 weeks and still going on, hope it improves soon and ill get back to this.

**Comment by ioolkos** [comment]
@codeadict oh, my... get well quick! & no stress about this here.

**Comment by codeadict** [comment]
Figured out the issue here @ioolkos . There is a backward-incompatible change in clique introduced in https://github.com/basho/clique/pull/74. While it made much sense for Riak, in VerneMQ there is a custom vmq_config and will need a lot of work to make it work with this new system, so will rather release a new version with my patch only on top of the version we were using because is not worth introducing so many changes for a simple bug.

**Comment by codeadict** [comment]
This works now @ioolkos, is failing due to unrelated tests that usually fail most likely due to timing on slow Travis machines, rebuilding the Travis job should fix it. This is using my fork now, which is version **0.3.6** of clique (we were on 0.3.4 and 0.3.7 is when basho introduced the breaking changes so from 0.3.4 to 0.3.6 some improvements were introduced to improve exit code handling so I thought that would be beneficial for us).  Fee free to use my branch to create a tag `0.3.6-verne` in the VerneMQ fork and I will update the rebar.config with it.

Screen Shot 2020-03-29 at 3 00 41 PM

**Comment by ioolkos** [comment]
Awesome, I'll look into it tomorrow. Thanks!

**Comment by ioolkos** [comment]
I created a tag 0.3.6-verne in vernemq/clique. But I somehow can't select this tag as a base branch when creating a PR from codeadict/clique.
I'm probably confused now, will give it a second try after more coffee.

**Comment by ioolkos** [comment]
Changed the base to branch rel_0.3.6-verne here https://github.com/vernemq/clique/pull/1
So maybe we can then use this branch in VerneMQ deps?

**Comment by codeadict** [comment]
Yeah perfectly fine to use the branch `rel_0.3.6-verne` once the PR https://github.com/vernemq/clique/pull/1 is merged, I'll update here when is done

**Comment by codeadict** [comment]
Done here

**Pull request merged**
