### PR TITLE
Updated Satheeshkumar allow all internal user without client_id

### PR DESCRIPTION
**Pull request by gsatheeshkumar**
Updated Satheeshkumar allow all internal user without client_id

## Proposed Changes

Please describe the big picture of your changes here to communicate to the
VerneMQ team why we should accept this pull request. If it fixes a bug or
resolves a feature request, be sure to link to that issue.

## Types of Changes

What types of changes does your code introduce to this project?
_Put an `x` in the boxes that apply_

- [ ] Bugfix (non-breaking change which fixes issue #XXXX)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] Documentation (correction or otherwise)
- [ ] Cosmetics (whitespace, styles...)
- [ ] DevOps (Build scripts, pipelines...)

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating
the PR. If you're unsure about any of them, don't hesitate to ask on the
mailing list. We're here to help! This is simply a reminder of what we are
going to look for before merging your code._

- [x] I have read the `CODE_OF_CONDUCT.md` document
- [ ] All tests pass locally with my changes
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation (if needed)
- [x] Any dependent changes have been merged and published in related repositories
- [ ] I have updated changelog (At the bottom of the release version)
- [ ] I have squashed all my commits into one before merging

## Further Comments

If this is a relatively large or complex change, kick off the discussion by
explaining why you chose the solution you did and what alternatives you
considered, etc.

### CODE REVIEW

**Comment by gsatheeshkumar** [comment]
I have approved

**Comment by ioolkos** [comment]
@gsatheeshkumar Thanks. I see this as a customization of the auth script (which is something you are welcome to do). I'm not sure this is a valid generic use case. It will allow the "internal" clients to grab sessions from other ClientIDs, in the worst case.

**Comment by gsatheeshkumar** [comment]
> @gsatheeshkumar Thanks. I see this as a customization of the auth script (which is something you are welcome to do). I'm not sure this is a valid generic use case. It will allow the "internal" clients to grab sessions from other ClientIDs, in the worst case.

It is very use full for auto scale Pod times. we are using past 2 years 1.10.0 version,Now are not able to build the image with customization, Can you please help me, How to build with customization  1.12.5 version and create image to dockerHub,  please

**Comment by ioolkos** [comment]
@gsatheeshkumar Apologies that I cannot offer free help for customization. I'm sure you'll find a way to achieve what you need.

---
:point_right: Thank you for supporting VerneMQ: https://github.com/sponsors/vernemq
:point_right: Using the binary VerneMQ packages commercially (.deb/.rpm/Docker) requires a paid subscription.

**Pull request closed without merging**
