### PR TITLE
Fix spelling in README

### PR DESCRIPTION
**Pull request by trarbr**

### CODE REVIEW

**Comment by larshesel** [comment]
Thanks!

**Comment by larshesel** [comment]
Hey @trarbr, would it be ok if I add you to the THANKS file? If you like you could add yourself :) let me know!

**Comment by trarbr** [comment]
I would be honored :) You can add `Troels Brødsgaard (@trarbr)`

**Comment by larshesel** [comment]
Done :) https://github.com/vernemq/vernemq/commit/0756671e59dc11860b8f5ece4e531fd8d2148798

**Pull request merged**
