### PR TITLE
Protect from subscription flood (vernemq/vernemq#988)

### PR DESCRIPTION
**Pull request by szymonk**
Switch to plumtree version which supports drop_i_have_threshold. This
allows to drop some messages instead of accumulating them infinitely
and not having CPU time to process them.

Since the modified plumtree version needs newer gen_server2, update it
globally.

### CODE REVIEW

**Comment by larshesel** [comment]
This looks good to me - I think it needs a changelog at the bottom of the current unreleased fixes (above 1.6.0). Maybe sth like:

```
- Add protection mechanism for the plumtree metadata store from subscription floods by dropping and not acknowledging `i_have` messages when the mailbox size grows above a certain threshold. This threshold is configurable via the `plumtree.drop_i_have_threshold` hidden option. The default is 1000000.
```

/cc @dergraf

**Comment by larshesel** [comment]
Thank you so much for this contribution!

**Comment by larshesel** [comment]
I completely forgot, may I add you to the THANKS.md file? Do you have other names than @szymonk  and @p3we - let me know what you prefer! Cheers!

**Comment by szymonk** [comment]
That would be great! We would prefer to be added as Artur Sobierak and Szymon Kałasz. Also, to credit the company we work for, could you please add a mention to `changelog.md` that this improvement has been contributed by ADB (https://www.adbglobal.com)?

**Comment by larshesel** [comment]
absolutely! will prepare a PR right away

**Comment by larshesel** [comment]
Something like this, would that be fine? https://github.com/vernemq/vernemq/pull/1014

**Comment by larshesel** [comment]
btw, we've been thinking a bit about how to improve the metadata throughput and we have some preliminary work in #1012 but there are still some challenges to overcome there. Maybe this would also be of interest to you when it's finished. The idea / observation is that usually when a client connects it also immediately subscribes. Currently this results in two writes to the metadata store (one that the client is there and the second that it now has a subscription), but if these two writes can be combined into one we can save 50% of the writes to the metadata store...

**Comment by szymonk** [comment]
Looks good!
The connect/subscription optimizations sounds interesting. Thanks for the info!

**Pull request merged**
