### PR TITLE
WIP: Fix tests

### LINKED ISSUE #2011: Tests failing on master
### To help us save time and help you faster

Tests consistently fail locally and in CI , they have been failing in CI for quite some time. @ioolkos not sure if this is a known issue , if there is another open one feel free to close this one. Also if you have some clues or info about when this started happening, it will be great to help fix.

### Environment

- VerneMQ Version: master branch
- OS: OSX, Ubuntu Linux
- Erlang/OTP version (if building from source): 24.1 but fails on all version in Github Actions

### Expected behaviour

- CT tests fail locally and on CI

### Actual behaviour

- Run `./rebar3 ct`, will notice failures like the following which seem to be an issue with clique?:

```erlang
vmq_cluster_SUITE ==> {{badmatch,
     {badrpc,
         {'EXIT',
             {{badarity,
                  {#Fun<vmq_config_cli.11.101367952>,
                   [["shared_subscription_policy"],"random"]}},
              [{clique_config,run_callback,3,
                   [{file,
                        "/Users/codeadict/Hack/vernemq/_build/default/lib/clique/src/clique_config.erl"},
                    {line,268}]},
               {clique_config,'-run_callback/1-lc$^1/1-1-',4,
                   [{file,
                        "/Users/codeadict/Hack/vernemq/_build/default/lib/clique/src/clique_config.erl"},
                    {line,259}]},
               {clique_config,run_callback,1,
                   [{file,
                        "/Users/codeadict/Hack/vernemq/_build/default/lib/clique/src/clique_config.erl"},
                    {line,259}]},
               {clique_config,set,2,
                   [{file,
                        "/Users/codeadict/Hack/vernemq/_build/default/lib/clique/src/clique_config.erl"},
                    {line,142}]},
               {clique_command,run,1,
                   [{file,
                        "/Users/codeadict/Hack/vernemq/_build/default/lib/clique/src/clique_command.erl"},
                    {line,87}]},
               {vmq_server_cli,command,2,
                   [{file,
                        "/Users/codeadict/Hack/vernemq/apps/vmq_server/src/vmq_server_cli.erl"},
                    {line,41}]},
               {vmq_server_cmd,set_config,2,[]}]}}}},
 [{vmq_cluster_SUITE,'-set_shared_subs_policy/2-fun-0-',2,
      [{file,
           "/Users/codeadict/Hack/vernemq/apps/vmq_server/test/vmq_cluster_SUITE.erl"},
       {line,904}]},
```

### PR DESCRIPTION
**Pull request by codeadict**
## Proposed Changes

Fixes #2011 

## Types of Changes

What types of changes does your code introduce to this project?
_Put an `x` in the boxes that apply_

- [ ] Bugfix (non-breaking change which fixes issue #XXXX)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation (correction or otherwise)
- [ ] Cosmetics (whitespace, styles...)
- [ ] DevOps (Build scripts, pipelines...)

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating
the PR. If you're unsure about any of them, don't hesitate to ask on the
mailing list. We're here to help! This is simply a reminder of what we are
going to look for before merging your code._

- [ ] I have read the `CODE_OF_CONDUCT.md` document
- [ ] All tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if needed)
- [ ] Any dependent changes have been merged and published in related repositories
- [ ] I have updated changelog (At the bottom of the release version)
- [ ] I have squashed all my commits into one before merging

## Further Comments

If this is a relatively large or complex change, kick off the discussion by
explaining why you chose the solution you did and what alternatives you
considered, etc.

### CODE REVIEW

**Comment by ioolkos** [comment]
@codeadict Did a full test run on the PR locally. Awesome, thanks! Do you want to update the draft status, or still WIP?

**Comment by codeadict** [comment]
@ioolkos there are still 6 failing tests in the SWC app

**Comment by ioolkos** [comment]
@codeadict thanks, jep. Local test runs pass SWC, but some stuff happening with the Github actions environment.

**Comment by ioolkos** [comment]
Must add I only test on OTP 24 locally.

**Comment by ioolkos** [comment]
@codeadict I'd like to incrementally merge this as is, to have it in in a new release. Is that ok with you?

**Comment by codeadict** [comment]
@ioolkos sounds good to me, is at least little bit better than it was and I have not had the time again to work on Verne :(

**Comment by ioolkos** [comment]
@codeadict still a great contribution, thank you so much! :)

**Pull request merged**
