### PR TITLE
Add support for systemd notify (start, watchdog)

### PR DESCRIPTION
**Pull request by mths1**
## Proposed Changes

systemd support is currently not optimal. As described in #1514 it is possible that systemd does not recognize a state change and thus e.g. does not restart the service accordingly. This change proposes:

- Use systemd library to support "notify" service type 
- Change the mainpid to run_erl (supervises) by systemd
- Use systemd-notify instead of pid files 

Example system-d unit:
# systemd unit file
[Unit]
Description=VerneMQ Server

[Service]
Type=notify
NotifyAccess=all
LimitNOFILE=100000
SuccessExitStatus=1
[...]
WatchdogSec = 30s
Restart = always

## Types of Changes

What types of changes does your code introduce to this project?
_Put an `x` in the boxes that apply_

- [x] Bugfix (non-breaking change which fixes issue #1514 )
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation (correction or otherwise)
- [ ] Cosmetics (whitespace, styles...)
- [ ] DevOps (Build scripts, pipelines...)

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating
the PR. If you're unsure about any of them, don't hesitate to ask on the
mailing list. We're here to help! This is simply a reminder of what we are
going to look for before merging your code._

- [ ] I have read the [CODE_OF_CONDUCT.md](https://github.com/vernemq/vernemq/blob/main/CODE_OF_CONDUCT.md) document
- [ ] All tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if needed)
- [ ] Any dependent changes have been merged and published in related repositories
- [ ] I have updated changelog (At the bottom of the release version)
- [ ] I have squashed all my commits into one before merging

## Further Comments

If this is a relatively large or complex change, kick off the discussion by
explaining why you chose the solution you did and what alternatives you
considered, etc.

### CODE REVIEW

**Comment by ioolkos** [comment]
Cool stuff, thanks! I wonder whether we could use this to have some cheap "boot states" instead of just "ready".  (think "listeners started", "subscriptions loaded").

**Comment by mths1** [comment]
systemd allows to set any status (here "custom status"). We would just need to know where to set the information and if it is ok to just have the latest status there indefinately or find a good place to really signal boot complete.

grafik

**Comment by ioolkos** [comment]
@mths1 I see, I'm looking into what makes sense to add.

**Comment by mths1** [comment]
@ioolkos : This should be "good enough" as a first version. There surely is room for improvement, but I am currently not working on this active anymore

**Review by ioolkos — APPROVED** [review]

**Pull request merged**
