### PR TITLE
added on_topic_unsubscribed/1 hook

### PR DESCRIPTION
**Pull request by khodzha**
issue at hand: https://github.com/vernemq/vernemq/issues/1326

@ioolkos

### CODE REVIEW

**Comment by ioolkos** [comment]
Thanks @khodzha.
Some things don't click for me. Can you confirm this implements your original issue? (it seemed to me it was about knowing which subscriptions were deleted in the plugin). I see though that this is more about *where* you want to call that hook, vs what the hook does.
We'll also need to think about the case where unsubscribe is not allowed due to CAP settings.

An alternative name would be `on_subscription_deleted` to move it away a little better from `on_unsubscribe`

**Comment by khodzha** [comment]
yeah, you are right
i added topics parameter and `CAPSettings#cap_settings.allow_unsubscribe` check

**Comment by codeadict** [comment]
This also will require tests and adding the hook to `vernemq_dev`.

**Comment by khodzha** [comment]
vernemq_dev pr:
https://github.com/vernemq/vernemq_dev/pull/14
not sure about naming of `maybe_topics()` type

**Comment by khodzha** [comment]
added tests

**Comment by khodzha** [comment]
`vmq_rate_limiter` were failing so i tried to fix  them in https://github.com/vernemq/vernemq/pull/1544

**Comment by khodzha** [comment]
@ioolkos any updates here? thanks

**Comment by ioolkos** [comment]
@khodzha aware you're waiting... thanks for your patience in any case.
Quick question: you added MQTT5 tests but only implemented the hook for MQTT4 FSM? what if the queue is connected to an MQTT5 session?

**Comment by khodzha** [comment]
@ioolkos thanks for catching this

the hook is already called from `vmq_reg:unsubscribe/3`
so i guess its not needed to call the hook explicitly in both FSMs, since there are these callback funs:
https://github.com/vernemq/vernemq/blob/947df6413e454adbf4cdbe5e9f7f92663d7858a3/apps/vmq_server/src/vmq_mqtt_fsm.erl#L406-L409
and
https://github.com/vernemq/vernemq/blob/947df6413e454adbf4cdbe5e9f7f92663d7858a3/apps/vmq_server/src/vmq_mqtt5_fsm.erl#L582-L585

**Comment by ioolkos** [comment]
Hm, I still think it needs to be in the FSMs. What if you land here: 
https://github.com/vernemq/vernemq/blob/947df6413e454adbf4cdbe5e9f7f92663d7858a3/apps/vmq_server/src/vmq_mqtt_fsm.erl#L415

You might have set an ID to unsubscribed in your plugin/DB, being actually still subscribed on the broker. So, I think you want to wait for the success case, and then call the plugin. Or possibly check for successful feedback of vmq_reg function in OnSuccess fun, bet then it'd still be in the FSM.
Hope this makes sense.

**Comment by khodzha** [comment]
@ioolkos sorry i maybe reading it wrong but i think `{error, _Reason}` clause is entered only when this branch is run and fails:
https://github.com/vernemq/vernemq/blob/947df6413e454adbf4cdbe5e9f7f92663d7858a3/apps/vmq_server/src/vmq_reg.erl#L104-L106

but `vmq_cluster:if_ready` shortcircuits without running `unsubscribe_op` if there is an error:
https://github.com/vernemq/vernemq/blob/947df6413e454adbf4cdbe5e9f7f92663d7858a3/apps/vmq_server/src/vmq_cluster.erl#L91-L97

**Comment by khodzha** [comment]
rebased on latest master

**Comment by khodzha** [comment]
@ioolkos

**Comment by ioolkos** [comment]
@khodzha it'd be the only plugin we call in `vmq_reg`. This might be ok, but it just makes me a little cautious. In the sense of either we can do it with other plugins too, or there is a reason we keep everything in the MQTT FSMs.

**Comment by khodzha** [comment]
i have no hard opinion on this, so why not
moved hook to FSMs

**Comment by ioolkos** [comment]
@khodzha thanks, merged.

**Pull request merged**
