### PR TITLE
Upgrade sext to latest version 1.5.0

### PR DESCRIPTION
**Pull request by codeadict**
Previous to this, I was having issues in OSX, after upgrading sext things are working fine on both OTP 19.x and 20.x.

Details of the error i was getting:

```erlang
[os_mon] cpu supervisor port (cpu_sup): Erlang has closed
{"Kernel pid terminated",application_controller,"{application_start_failure,vmq_server,{{shutdown,{failed_to_start_child,vmq_lvldb_store_sup,{'EXIT',{{badmatch,{error,{{{undef,[{sext,encode,[{{vmq,config},{'VerneMQ@127.0.0.1',vmq_server,msg_store_opts}}],[]},{plumtree_metadata_leveldb_instance,handle_call,3,[{file,\"/Users/codeadict/dev/vernemq/_build/default/lib/plumtree/src/plumtree_metadata_leveldb_instance.erl\"},{line,155}]},{gen_server,try_handle_call,4,[{file,\"gen_server.erl\"},{line,636}]},{gen_server,handle_msg,6,[{file,\"gen_server.erl\"},{line,665}]},{proc_lib,init_p_do_apply,3,[{file,\"proc_lib.erl\"},{line,247}]}]},{gen_server,call,[plmtrlvld_6,{get,{{vmq,config},{'VerneMQ@127.0.0.1',vmq_server,msg_store_opts}}},infinity]}},{child,undefined,{vmq_lvldb_store_bucket,1},{vmq_lvldb_store,start_link,[1]},permanent,5000,worker,[vmq_lvldb_store]}}}},[{vmq_lvldb_store_sup,'-start_link/0-lc$^0/1-0-',2,[{file,\"/Users/codeadict/dev/vernemq/_build/default/lib/vmq_server/src/vmq_lvldb_store_sup.erl\"},{line,38}]},{vmq_lvldb_store_sup,start_link,0,[{file,\"/Users/codeadict/dev/vernemq/_build/default/lib/vmq_server/src/vmq_lvldb_store_sup.erl\"},{line,37}]},{supervisor,do_start_child,2,[{file,\"supervisor.erl\"},{line,365}]},{supervisor,start_children,3,[{file,\"supervisor.erl\"},{line,348}]},{supervisor,init_children,2,[{file,\"supervisor.erl\"},{line,314}]},{gen_server,init_it,2,[{file,\"gen_server.erl\"},{line,365}]},{gen_server,init_it,6,[{file,\"gen_server.erl\"},{line,333}]},{proc_lib,init_p_do_apply,3,[{file,\"proc_lib.erl\"},{line,247}]}]}}}},{vmq_server_app,start,[normal,[]]}}}"}
Kernel pid terminated (application_controller) ({application_start_failure,vmq_server,{{shutdown,{failed_to_start_child,vmq_lvldb_store_sup,{'EXIT',{{badmatch,{error,{{{undef,[{sext,encode,[{{vmq,conf
```

**Note:** I think plumtree needs to be upgraded also. Isn't it?

### CODE REVIEW

**Comment by larshesel** [comment]
Looks good to me, but I'll let @dergraf decide as maybe there's an impact on the SWC work?

**Comment by codeadict** [comment]
Need to resolve conflict here once the status page one is merged, otherwise will have conflicts again :)

**Comment by larshesel** [comment]
Just merged the status page!

**Comment by codeadict** [comment]
Done!

**Pull request merged**
