### PR TITLE
WIP: RocksDB, Leveled

### PR DESCRIPTION
**Pull request by ioolkos**

### CODE REVIEW

**Comment by codeadict** [comment]
How is this feature going @ioolkos ? Anything i can help with?

**Comment by ioolkos** [comment]
@codeadict thanks for asking! :)
I'm thankful for any input/help and it's a good opportunity to come back to this for me. What I have not yet tackled is to integrate the RocksDB config (as seen in the example advanced config file in this PR) vals into the `vernemq.conf` file. To be honest, I'm not sure all will be needed, but OTOH if we expose some, we could as well just go for all.

Other than that, we need to update everything in the branch here, make sure it runs on OTP 24, make sure the test suites go through with a RocksDB build.

There's also full Leveled support hidden in the PR :) Same as above applies, although I don't even think we need to configure much via `vernemq.conf` file.

**Comment by codeadict** [comment]
Sounds good @ioolkos , doesn't seem like a hard task, although there is a lot of details in RocksDB config. Should I bring `vernemq:feature-rocksdb-messagestore` up to date with master? Then i will start working on my own based on this one

**Comment by ioolkos** [comment]
> Should I bring `vernemq:feature-rocksdb-messagestore` up to date with master? Then i will start working on my own based on this one

Awesome :) yeah I think that's the best approach.

**Comment by codeadict** [comment]
Alright, it is up to date here https://github.com/codeadict/vernemq/tree/feature-rocksdb-messagestore

**Comment by ioolkos** [comment]
@codeadict I created the `new-feature-rocksdb-messagestore` branch here, including the commit from your branch.
For now, I'll keep RocksDB config in the advanced.config file; better to give users something to experiment.
Closing this PR in favour of new branch.

**Pull request closed without merging**
