### PR TITLE
Introduce vmq_admin session unsubscribe command

### PR DESCRIPTION
**Pull request by mths1**
## Proposed Changes

Introduces new command 
vmq-admin session unsubscribe client-id=xxx topic=yyy

## Types of Changes

What types of changes does your code introduce to this project?
_Put an `x` in the boxes that apply_

- [ ] Bugfix (non-breaking change which fixes issue #XXXX)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation (correction or otherwise)
- [ ] Cosmetics (whitespace, styles...)
- [ ] DevOps (Build scripts, pipelines...)

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating
the PR. If you're unsure about any of them, don't hesitate to ask on the
mailing list. We're here to help! This is simply a reminder of what we are
going to look for before merging your code._

- [ ] I have read the [CODE_OF_CONDUCT.md](https://github.com/vernemq/vernemq/blob/main/CODE_OF_CONDUCT.md) document
- [ ] All tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if needed)
- [ ] Any dependent changes have been merged and published in related repositories
- [ ] I have updated changelog (At the bottom of the release version)
- [ ] I have squashed all my commits into one before merging

## Further Comments

If this is a relatively large or complex change, kick off the discussion by
explaining why you chose the solution you did and what alternatives you
considered, etc.

### CODE REVIEW

**Review by ioolkos — DISMISSED** [review]
Nice addition, thanks!

**Comment by mths1** [comment]
Let me know, if you see some point in also having the subscribe cmd as well. We implemented unsubscribe because it "persistent session" support is sometimes quite hard to manage client-side, and thus we sometimes needed some quick fix :-)

**Comment by ioolkos** [comment]
@mths1 do you have a need for the `subscribe` command as well, or shall I merge this as is for now?

**Comment by mths1** [comment]
@ioolkos : Let's merge this. We had same cases, where an unsubscribe would have been handy but none for a subscribe so far.

**Pull request merged**
